spring.application.name=workout

spring.datasource.url=jdbc:postgresql://localhost:5432/workout
spring.datasource.username=workout
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET}
jwt.expiration-time=${JWT_EXPIRATION_TIME:3600000}